### ISSUE TITLE
USER STORY:Anonymus feedback

### ISSUE THREAD

**Issue by noemichis** [noemichis/First-Agile-Project#3]
In order to **give my feedback anonymously** as a **user**, I can **choose to hide my name in the poll**

## Acceptance critera:
* a. A checkbox should be included to hide name.
* b. The checkbox should be selected by default.
* c. The checlbox should be next to the submit button
  
## Tasks
- [ ] Update HTML and CSS by creating a checkbox.
- [ ] Add username field.
- [ ] Verify checkbox functionality.
